document.writeln('<table border = 1>');
document.writeln('<tr>');
document.writeln('<td>' + "Свойство" + '</td>');
document.writeln('<td>' + "Значение" + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.href" + '</td>');
document.writeln('<td>' + location.href + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.host" + '</td>');
document.writeln('<td>' + location.host + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.hash" + '</td>');
document.writeln('<td>' + location.hash + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.port" + '</td>');
document.writeln('<td>' + location.port + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.protocol" + '</td>');
document.writeln('<td>' + location.protocol + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "location.search" + '</td>');
document.writeln('<td>' + location.search + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "navigator.appName" + '</td>');
document.writeln('<td>' + navigator.appName + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "navigator.userAgent" + '</td>');
document.writeln('<td>' + navigator.userAgent + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "navigator.cookieEnabled" + '</td>');
document.writeln('<td>' + navigator.cookieEnabled + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "navigator.javaEnabled()" + '</td>');
document.writeln('<td>' + navigator.javaEnabled() + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "navigator.onLine" + '</td>');
document.writeln('<td>' + navigator.onLine + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "innerHeight" + '</td>');
document.writeln('<td>' + innerHeight + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "innerWidth" + '</td>');
document.writeln('<td>' + innerWidth + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screenX" + '</td>');
document.writeln('<td>' + screenX + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screenY" + '</td>');
document.writeln('<td>' + screenY + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "scrollX" + '</td>');
document.writeln('<td>' + scrollX + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "scrollY" + '</td>');
document.writeln('<td>' + scrollY + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.width" + '</td>');
document.writeln('<td>' + screen.width + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.height" + '</td>');
document.writeln('<td>' + screen.height + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.availHeight" + '</td>');
document.writeln('<td>' + screen.availHeight + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.availWidth" + '</td>');
document.writeln('<td>' + screen.availWidth + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.colorDepth" + '</td>');
document.writeln('<td>' + screen.colorDepth + '</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td>' + "screen.orientation.type" + '</td>');
document.writeln('<td>' + screen.orientation.type + '</td>');
document.writeln('</tr>');
document.writeln('</table>');